name: Publish Docker
on: 
  push:
    branches:    
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        dockerfile: API/Dockerfile
        name: docker.pkg.github.com/kristianfjones/vcenter-networks/vcenter-network
        username: ${{ secrets.DOCKER_GITHUB_USERNAME }}
        password: ${{ secrets.DOCKER_GITHUB_PASSWORD }}
        registry: docker.pkg.github.com
